/**
 * WinRAR curve configuration.
 * Port of WinRarConfig from C++ codebase.
 * 
 * Curve: y^2 + xy = x^3 + Ax^2 + B over GF((2^15)^17)
 * A = 0 (zero element)
 * B = element with Items[0] = 161
 */

import { gfZero, gfFromItems } from "./GaloisField";
import type { ECCurve, ECPoint } from "./EllipticCurve";
import { ecPointFromCoords } from "./EllipticCurve";

// Curve parameters
export const CURVE: ECCurve = {
  A: gfZero(),
  B: gfFromItems([161]),
};

// Generator point G
export const G: ECPoint = ecPointFromCoords(
  CURVE,
  gfFromItems([
    0x38cc, 0x052f, 0x2510, 0x45aa, 0x1b89, 0x4468, 0x4882, 0x0d67,
    0x4feb, 0x55ce, 0x0025, 0x4cb7, 0x0cc2, 0x59dc, 0x289e, 0x65e3,
    0x56fd,
  ]),
  gfFromItems([
    0x31a7, 0x65f2, 0x18c4, 0x3412, 0x7388, 0x54c1, 0x539b, 0x4a02,
    0x4d07, 0x12d6, 0x7911, 0x3b5e, 0x4f0e, 0x216f, 0x2bf2, 0x1974,
    0x20da,
  ])
);

// Order of the generator point
export const ORDER = BigInt(
  "0x1026dd85081b82314691ced9bbec30547840e4bf72d8b5e0d258442bbcd31"
);

// Private key (generated by GeneratePrivateKey(nullptr, 0))
export const PRIVATE_KEY = BigInt(
  "0x59fe6abcca90bdb95f0105271fa85fb9f11f467450c1ae9044b7fd61d65e"
);

// Public key point
export const PUBLIC_KEY: ECPoint = ecPointFromCoords(
  CURVE,
  gfFromItems([
    0x3a1a, 0x1109, 0x268a, 0x12f7, 0x3734, 0x75f0, 0x576c, 0x2ea4,
    0x4813, 0x3f62, 0x0567, 0x784d, 0x753d, 0x6d92, 0x366c, 0x1107,
    0x3861,
  ]),
  gfFromItems([
    0x6c20, 0x6027, 0x1b22, 0x7a87, 0x43c4, 0x1908, 0x2449, 0x4675,
    0x7933, 0x2e66, 0x32f5, 0x2a58, 0x1145, 0x74ac, 0x36d0, 0x2731,
    0x12b6,
  ])
);
